version: '3'

services:
  oidc:
    build: 
      context: ./oidc-ui
      dockerfile: Dockerfile
    image: oidc:latest
    restart: always
    ports:
      - "3000:3000"

  relyparty_api:
    build: 
      context: ./partyservice
      dockerfile: Dockerfile
    image: relyparty_api:latest
    restart: always
    ports:
      - "8888:8888"

  relyparty_ui:
    build: 
      context: ./relyingPatryUI
      dockerfile: Dockerfile
    image: relyparty_ui:latest
    restart: always
    ports:
      - "5000:5000"
